spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: wishlistdb
      username: admin
      password: password
      repositories:
        enabled: true


server:
  port:
    5000
